"""Public package surface for ml4t-models."""

__version__ = "0.1.0a0"

from ml4t.models.api import (
    AssetMapper,
    FactorForecaster,
    LatentFactorModel,
    PortfolioModel,
    PortfolioPostprocessor,
    StochasticDiscountFactorEstimator,
)
from ml4t.models.configs import (
    AR1ForecasterConfig,
    CAEConfig,
    DeepPortfolioConfig,
    EWMABaseForecasterConfig,
    ExpandingMeanForecasterConfig,
    IPCAConfig,
    LatentFactorConfig,
    LinearPortfolioConfig,
    LSTMPortfolioConfig,
    MapperConfig,
    PCAConfig,
    PipelineConfig,
    PortfolioConfig,
    SAEConfig,
    StochasticDiscountFactorConfig,
)
from ml4t.models.forecasters import (
    AR1FactorForecaster,
    EWMABaseFactorForecaster,
    ExpandingMeanFactorForecaster,
)
from ml4t.models.integration import (
    ResolvedDatasetSchema,
    SurfaceFrame,
    cross_section_batch_from_long_frame,
    persistent_panel_batch_from_long_frame,
    prediction_surface_from_asset_forecast,
    resolve_dataset_schema,
    signal_surface_from_portfolio_weights,
    weight_surface_from_portfolio_weights,
    write_backtest_surfaces,
)
from ml4t.models.latent_factors import CAEModel, IPCAModel, PCAModel, SAEModel
from ml4t.models.mappers import BetaLambdaMapper
from ml4t.models.pipelines import (
    LatentFactorForecastPipeline,
    PortfolioAllocationPipeline,
    PortfolioPipelineFitResult,
)
from ml4t.models.portfolio import (
    DeepPortfolioModel,
    LinearFeaturePortfolioModel,
    LSTMPortfolioModel,
    WeightConstraintPostprocessor,
)
from ml4t.models.stochastic_discount_factor import (
    LinearStochasticDiscountFactorReturnMapper,
    StochasticDiscountFactorModel,
)
from ml4t.models.types import (
    AssetForecastResult,
    AssetWeightsResult,
    CrossSectionBatch,
    FactorForecastResult,
    FitSummary,
    LatentFactorPrediction,
    LatentFactorState,
    PersistentPanelBatch,
    PortfolioPrediction,
    PortfolioSequenceBatch,
    PortfolioWeightsResult,
    StochasticDiscountFactorState,
)

__all__ = [
    "AssetForecastResult",
    "AR1FactorForecaster",
    "AR1ForecasterConfig",
    "AssetMapper",
    "BetaLambdaMapper",
    "AssetWeightsResult",
    "CAEConfig",
    "CAEModel",
    "CrossSectionBatch",
    "DeepPortfolioConfig",
    "DeepPortfolioModel",
    "EWMABaseFactorForecaster",
    "EWMABaseForecasterConfig",
    "ExpandingMeanFactorForecaster",
    "ExpandingMeanForecasterConfig",
    "FactorForecaster",
    "FactorForecastResult",
    "FitSummary",
    "IPCAConfig",
    "IPCAModel",
    "LatentFactorConfig",
    "LatentFactorForecastPipeline",
    "LatentFactorModel",
    "LatentFactorPrediction",
    "LatentFactorState",
    "LinearFeaturePortfolioModel",
    "LinearPortfolioConfig",
    "LSTMPortfolioConfig",
    "LSTMPortfolioModel",
    "LinearStochasticDiscountFactorReturnMapper",
    "MapperConfig",
    "PCAConfig",
    "PCAModel",
    "PersistentPanelBatch",
    "PipelineConfig",
    "PortfolioAllocationPipeline",
    "PortfolioConfig",
    "PortfolioPipelineFitResult",
    "PortfolioPostprocessor",
    "PortfolioPrediction",
    "PortfolioModel",
    "PortfolioSequenceBatch",
    "PortfolioWeightsResult",
    "SAEConfig",
    "SAEModel",
    "ResolvedDatasetSchema",
    "SurfaceFrame",
    "cross_section_batch_from_long_frame",
    "persistent_panel_batch_from_long_frame",
    "prediction_surface_from_asset_forecast",
    "resolve_dataset_schema",
    "signal_surface_from_portfolio_weights",
    "StochasticDiscountFactorConfig",
    "StochasticDiscountFactorEstimator",
    "StochasticDiscountFactorModel",
    "StochasticDiscountFactorState",
    "weight_surface_from_portfolio_weights",
    "WeightConstraintPostprocessor",
    "write_backtest_surfaces",
]
